from setuptools import setup

setup(
    name="bibtex-dblp",
    version="0.5",
    author="M. Volk",
    author_email="matthias.volk@cs.rwth-aachen.de",
    maintainer="M. Volk",
    maintainer_email="matthias.volk@cs.rwth-aachen.de",
    url="https://github.com/volkm/bibtex-dblp",
    description="Create and revise bibtex entries from DBLP.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    packages=["bibtex_dblp"],
    entry_points={"console_scripts": ["dblp = bibtex_dblp.cli:main"]},
    install_requires=["Click", "pybtex", "requests"],
    setup_requires=["pytest-runner"],
    tests_require=["pytest"],
    extras_require={"dev": ["flake8", "black", "isort", "pytest", "mypy"]},
    python_requires=">=3",
    zip_safe=False,
    platforms="any",
    classifiers=[
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
        "Natural Language :: English",
        "Programming Language :: Python :: 3",
        "Topic :: Utilities",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
    ],
)
